services:
  - type: web
    name: diet-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 5000
      - key: 7708407032:AAEIPAhw7khIzc1L0Q6MEhhjo7iXsEyKgWs
        sync: false  # توکن را دستی در پنل تنظیم کنید
