services:
  - type: web
    name: diet-bot
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 5000
      - key: TELEGRAM_TOKEN
        sync: false
    healthCheckPath: /health
