services:
  - type: web
    name: diet-bot
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 5000
      - key: TELEGRAM_TOKEN
        value: your_bot_token_here
