services:
  - type: web
    name: diet-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: "توکن"
      - key: WEBHOOK_URL
        value: "https://your-render-app-url.onrender.com"
