services:
  - type: web
    name: diet-bot
    plan: free
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 5000
    healthCheckPath: /health
    autoDeploy: false  # جلوگیری از deploy خودکار
