services:
  - type: worker
    name: telegram-bot
    env: python
    plan: free         # یا starter/pro بسته به نیاز
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
